### ISSUE TITLE
[scripting API question] Getting and setting text items?

### ISSUE THREAD

**Issue by stormyweathers** [MitjaNemec/Kicad_action_plugins#131]
Hey there,

Thanks for your help last time, hope you have some insight to share again.
In the graphical board editor, I can create additional text items for any footprint.  However, I don't see a way to read or write these text items using the scripting API.  Theres nothing like GetText/SetText, TextItemsList, etc...

Do you have any clues for this?

Thanks,
Storm

**Comment by MitjaNemec** [comment]
You'll have to be more specific

1. Which KiCad version are you on? 5.1.x. or 5.99?
2. Does "graphical board editor" editor refer to footprint editor or pcbnew (board editor)? Just making sure, because you can not edit footprints directly in pcbnew (board editor).
3. [get_module_text_items](https://github.com/MitjaNemec/Kicad_action_plugins/blob/2d2c665d1d369fda3492c8a89ac307b8370daf38/replicate_layout/replicatelayout.py#L103) shows how you can grab text items in 5.1.x
