### ISSUE TITLE
archive_project doesn't archive the page layout description file

### ISSUE THREAD

**Issue by Sembazuru** [MitjaNemec/Kicad_action_plugins#53]
As the title says, a configured page layout file isn't archived so does not become portable.

I'd like the archive_project to copy the defined page layout file for both schematic and pcb to the project folder and then redirect the path to the project directory.

The setting for the page layout for both EEschema and PCBNew is in the project .pro file, so that might make this difficult...

**Comment by MitjaNemec** [comment]
Thanks for reporting it (I think it was mentioned before either on kicad-info forum or within some issue here on GitHub) so that it will not be forgotten.

As you said this is probably not doable as KiCad manager might rewrite any changes that are made from within the pcbnew. I'll try this out and see where it gets me. If you could supply a test project along with page layout description this would be even better.

**Comment by MitjaNemec** [comment]
@Sembazuru, I've pushed an implementation of worksheet archivation in the archive_worksheet branch. It works on windows and if you can test it on any other OS I'd appreciate it.

**Comment by Sembazuru** [comment]
Unfortunately for testing, I only have access to Windows as well.

**Comment by MitjaNemec** [comment]
Merged to master
